name: E2E Test CLI Apps

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
#      - master
      - '**'

jobs:
  e2e-webpack:
    name: E2E Webpack
    runs-on: ubuntu-latest
    services:
      redis:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
    steps:
    - uses: actions/checkout@v2
    - name: npm-verbosity
      run: npm config set loglevel verbose
    - name: npm-set-registry
      run: npm set registry http://0.0.0.0:4873
    - name: Use Webpack app
      run: |
        cd e2e
        cd examples
        cd webpack-app
        npm install
        npm run build
    - name: compile webpack
      run: ls -lsa e2e/examples/webpack-app
  e2e-angular:
    name: E2E Angular
    runs-on: ubuntu-latest
    services:
      redis:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: npm-verbosity
        run: npm config set loglevel verbose
      - name: npm-set-registry
        run: npm set registry http://0.0.0.0:4873
      - name: install angular-cli
        run: npm install -g @angular/cli
      - name: Use Angular CLI
        run: |
          cd e2e
          cd examples
          ng new angular-app
          cd angular-app
          npm install
          ng build
      - name: list angular
        run: ls -lsa e2e/examples/angular-app
