name: E2E Test Latest Verdaccio

on: [push]

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    services:
      redis:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
    steps:
    - name: 'Use Node.js 13.x'
      uses: actions/setup-node@master
      with:
       node-version: 13.x
    - name: npm-verbosity
      run: npm config set loglevel verbose
    - name: npm-set-registry
      run: npm set registry http://0.0.0.0:4873
    - name: npm-info-test
      run: npm info verdaccio


