name: E2E Test Webpack app

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
#      - master
      - '**'

jobs:
  e2e-npm:
    name: E2E npm
    runs-on: ubuntu-latest
    services:
      redis:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
    steps:
    - uses: actions/checkout@master
    - name: npm-verbosity
      run: npm config set loglevel verbose
    - name: npm-set-registry
      run: npm set registry http://0.0.0.0:4873
    - name: Use Webpack app
      run: |
        cd e2e
        cd examples
        cd webpack-app
        npm install
    - name: compile webpack
      run: ls -lsa
