name: E2E Test CRA Latest Verdaccio

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
#      - master
      - '**'

jobs:
  e2e-npm:
    strategy:
      fail-fast: true
      matrix:
        node_version: [10, 12, 13]
    name: E2E npm
    runs-on: ubuntu-latest
    services:
      redis:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
    steps:
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node_version: ${{ matrix.node_version }}
    - name: npm-verbosity
      run: npm config set loglevel verbose
    - name: npm-set-registry
      run: npm set registry http://0.0.0.0:4873
    - name: install latest npm
      run: npm -g i npm
    - name: create-react-app example
      run: |
        npx create-react-app --use-npm my-cra-ts --template typescript && cd my-cra-ts
        npm build
  e2e-yarn:
    name: E2E yarn
    strategy:
      fail-fast: false
      matrix:
        node_version: [10, 12, 13]
    runs-on: ubuntu-latest
    services:
      redis:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
    steps:
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: npm-verbosity
        run: npm config set loglevel verbose
      - name: npm-set-registry
        run: npm set registry http://0.0.0.0:4873
      - name: install latest yarn
        run: npm -g i yarn
      - name: create-react-app example
        run: |
          npx create-react-app my-cra-ts --template typescript && cd my-cra-ts
          yarn build
