name: E2E Test Latest Verdaccio

on: [push]

jobs:
  services:
    redis:
      image: verdaccio/verdaccio
      ports:
        - 4873:4873
  e2e:
    name: E2E
    runs-on: ubuntu-latest
     steps:
     - name: 'Use Node.js 13.x'
       uses: actions/setup-node@master
       with:
         node-version: 13.x

